baseURL = ""
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "异想萌域"                    # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 10                         # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                 # your google analytics id
disqusShortname = ""                 # your discuss shortname

[author]                             # essential                     # 必需
  name = "Sandeepin"

[blackfriday]
  smartypants = false

# [[menu.main]]                        # config your menu  # 配置菜单
#   name = "首页"
#   weight = 10
#   identifier = "home"
#   url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archive"
  url = "/moe/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
#[[menu.main]]
#  name = "关于"
#  weight = 40
#  identifier = "about"
#  url = "/about/"

[params]
  subTitle = "异想家的生活志"                                       # site's subTitle  # 网站二级标题
  footerSlogan = ""                                          # site's footer slogan  # 网站页脚标语
  keywords = ["Sandeepin", "异想博客","Hugo"]                                  # site's keywords  # 网站关键字
  description = "异想家的生活志"                        # site's description  # 网站描述

# mathjax
  enableMathJax = false                                                 # enable mathjax  # 是否使用mathjax（数学公式）

  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

[social]
  github = "https://github.com/jiangfangzheng/"
  weibo = "https://weibo.com/sandeepin"

# markdown中可以使用HTML标签，自己的博客不担心不安全
[markup.goldmark.renderer]
unsafe = true

# 解决代码高亮黑边问题 https://github.com/xiaoheiAh/hugo-theme-pure/issues/56
PygmentsCodeFences = false